---
# ===============================================================
# packages: install the necessary packages
# ===============================================================

- name: Install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - software-properties-common
    - python3-software-properties
    - libcache-perl
    - libcache-cache-perl
    - libwww-perl
    - python3-passlib
    - libcgi-fast-perl
    - libapache2-mod-fcgid
    - php7.3-cgi
    - munin
    - munin-node
    - munin-plugins-extra
  tags: packages
