---
# handlers file for ansible-role-munin

- name: restart apache
  become: yes
  service: name=apache2 state=restarted

- name: restart munin-node
  become: yes
  service: name=munin-node state=restarted
